"""create mark model

Revision ID: de6861c92cd8
Revises: 93e59b4abc34
Create Date: 2023-07-05 12:26:10.134808

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6861c92cd8'
down_revision = '93e59b4abc34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(),
                        nullable=True),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark')
    # ### end Alembic commands ###
